### ISSUE TITLE
Where can I find uf2conv?

### ISSUE THREAD

**Issue by janhoogerbrugge** [lowRISC/sonata-system#104]
Where can I find (the right) uf2conv?

Jan.

**Comment by marnovandermaas** [comment]
Please use the Nix environment, which has the `uf2conv` included, follow these instructions: https://github.com/lowRISC/sonata-software/blob/main/README.md
You can see which version it pulls in here: https://github.com/lowRISC/lowrisc-nix/blob/34f1d472d6066a42c684416f5e9e755d25ec6270/pkgs/uf2conv.nix
