### ISSUE TITLE
mdBook copies everything to book folder

### ISSUE THREAD

**Issue by marnovandermaas** [lowRISC/sonata-system#15]
During the documentation building, mdBook copies everything from the root directory into the `book` directory. I found this out because FuseSoC was using an old core file located in the `book` directory instead of using the most recent changes in root.

Is there any way that we can fix this? Should we limit mdBook generation to just within the `doc` folder?

**Comment by marnovandermaas** [comment]
@HU90m, @hcallahan-lowrisc and @GregAC for visibility.

**Comment by HU90m** [comment]
This is a known [complaint](https://github.com/rust-lang/mdBook/issues/1187) upstream. I have a nix build that ignores all files that aren't related to documentation. I'll open a PR once I get the preprocessors working.

**Comment by hcallahan-lowrisc** [comment]
> This is a known [complaint](https://github.com/rust-lang/mdBook/issues/1187) upstream.

Yeah it would be nice to have an upstream fix for this. It is definitely inconvenient when your docs are interspersed with code. I think fusesoc has a FUSESOC_IGNORE file or something similar to exclude a directory from searching for .core files, that could be a band-aid for now?

> I have a nix build that ignores all files that aren't related to documentation. I'll open a PR once I get the preprocessors working.

I have a branch with a working nix flake to build the OpenTitan site, might be helpful as a reference for the preprocessors. https://github.com/hcallahan-lowrisc/opentitan/blob/nix_site_build/util/site/flake.nix

**Comment by HU90m** [comment]
A little update.

I have a nix build that works around this in a branch of symphony: https://github.com/HU90m/symphony-system/tree/nix-mdbook

I'd like to get to move this nix app into lowrisc-nix because it will be common to both sonata and symphony (and possibly future repos as well).

**Comment by marnovandermaas** [comment]
I'm going to close this issue since the documentation update https://github.com/lowRISC/sonata-system/pull/19, the issue already being tracked upstream and the potential nix workaround.
