### ISSUE TITLE
SRAM address aliasing when HyperRAM is enabled

### ISSUE THREAD

**Issue by djlowther** [lowRISC/sonata-system#228]
When HyperRAM is enabled, the the SRAM address bus is only 17 bits wide but  `ADDR_MASK_SRAM` is still `32'h 0003ffff`, leading to reads from/writes to addresses 0x00120000-0x0013ffff being accepted but accessing the same physical memory as 0x00100000-0x0011ffff.

**Comment by marnovandermaas** [comment]
Yes, we need to change the size of the SRAM to `0x00020000` when HyperRAM is disabled here: https://github.com/lowRISC/sonata-system/blob/e73c4574b44dfaabbf57d2418beb3e1fca86e240/data/xbar_main.hjson#L38
We probably need to remove the automatically generated files and get them to be generated by FuseSoC based on the DisableHyperRam flag: https://github.com/lowRISC/sonata-system/blob/e73c4574b44dfaabbf57d2418beb3e1fca86e240/sonata.core#L87
