### ISSUE TITLE
Broken link in FPGA development

### ISSUE THREAD

**Issue by benlaurie** [lowRISC/sonata-system#88]
https://github.com/lowRISC/sonata-system/blob/main/doc/dev/fpga-development.md tells me to make sure I follow the software section. There is no software section.

**Comment by marnovandermaas** [comment]
It means the instructions in this section: https://lowrisc.org/sonata-system/doc/guide/building-examples.html

**Comment by marnovandermaas** [comment]
Opened a PR to fix this: https://github.com/lowRISC/sonata-system/pull/89
