### ISSUE TITLE
Documentation: Placeholders & Todos

### ISSUE THREAD

**Issue by colinoflynn** [lowRISC/sonata-system#93]
Tracking item from #91

`fpga-update.md`:
- [ ] Do we want to recommend a "user slot"? I specified 'slot 2'. If that is OK remove [this todo](https://github.com/lowRISC/sonata-system/blob/main/doc/guide/fpga-update.md?plain=1#L27).
- [ ] Link to bitstream - remove [this todo](https://github.com/lowRISC/sonata-system/blob/main/doc/guide/fpga-update.md?plain=1#L31) and [update URL](https://github.com/lowRISC/sonata-system/blob/main/doc/guide/fpga-update.md?plain=1#L35). Also update [wget example](https://github.com/lowRISC/sonata-system/blob/main/doc/guide/fpga-update.md?plain=1#L52) if you want to support that.

`toolchain-setup.md`:
- [ ] Add link to WSL2 PR, tell users to check if that was committed *before* blindly applying the patch.

`building-examples.md`:
- [ ] These instructions were written inbetween the build system change - are the [environmental variables](https://github.com/lowRISC/sonata-system/blob/main/doc/guide/building-examples.md?plain=1#L34) needed? Update my [TODO](https://github.com/lowRISC/sonata-system/blob/main/doc/guide/building-examples.md?plain=1#L49) in addition to fixing docs.
- [ ] Update link to [SW Download](https://github.com/lowRISC/sonata-system/blob/main/doc/guide/building-examples.md?plain=1#L46) - maybe tell people to checkout specific tag matching the release is easier? Or do they just download SW code release?

**Comment by marnovandermaas** [comment]
Many of this is fixed in my PR: https://github.com/lowRISC/sonata-system/issues/91

**Comment by colinoflynn** [comment]
I was way too slow in the GIT race!
