### ISSUE TITLE
xmake is not listed as a prerequistie

### ISSUE THREAD

**Issue by benlaurie** [lowRISC/sonata-system#97]

**Comment by marnovandermaas** [comment]
Thanks Ben! I recently split the software toolchain setup page into a Nix and a manual setup. The Nix setup should point you to the sonata software repository and `xmake` is included in the Nix environment: https://lowrisc.org/sonata-system/doc/guide/toolchain-setup.html?highlight=requi#nix-setup

**Comment by benlaurie** [comment]
OK, but it isn't included in the manual setup.

**Comment by davidchisnall** [comment]
Please can you point people at the CHERIoT docs, rather than trying to duplicate half of them?

**Comment by marnovandermaas** [comment]
Ok, I've listed xmake as a dependency for Sonata software and have linked to the CHERIoT RTOS documentation for a full development setup: https://github.com/lowRISC/sonata-system/pull/260
